name: docs-ci

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs-ci.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs-ci.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: "docs/pnpm-lock.yaml"
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: docs

      - name: Build
        run: pnpm run build
        working-directory: docs
