name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write # This is important for label creation
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      # Don't use release_created this: https://danwakeem.medium.com/beware-the-release-please-v4-github-action-ee71ff9de151
      # releases_created: ${{ steps.release.outputs.releases_created }}
      # paths_released: ${{ steps.release.outputs.paths_released }}
      # JavaScript outputs
      javascript--release_created: ${{ steps.release.outputs['javascript--release_created'] }}
      javascript--tag_name: ${{ steps.release.outputs['javascript--tag_name'] }}
      # Python outputs
      python--release_created: ${{ steps.release.outputs['python--release_created'] }}
      python--tag_name: ${{ steps.release.outputs['python--tag_name'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Use manifest mode for monorepo
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Echo outputs
        shell: bash
        env:
          RELEASE_OUTPUTS: ${{ toJSON(steps.release.outputs) }}
        run: |
          echo "All release-please outputs:"
          printf '%s\n' "$RELEASE_OUTPUTS"

      - name: Publish JavaScript
        if: ${{ steps.release.outputs.javascript--release_created }}
        uses: ./.github/workflows/javascript-publish.yml

      - name: Publish Python
        if: ${{ steps.release.outputs.python--release_created }}
        uses: ./.github/workflows/python-publish.yml
